[package]
name = "radias-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "radias-rust"
path = "src/main.rs"

[dependencies]
radias-domain = { path = "../radias-domain" }
radias-application = { path = "../radias-application" }
radias-infrastructure = { path = "../radias-infrastructure" }
serde_json = "=1.0.151"
