import {MODULES,EXTRA_MODULES,outputPorts,availableModules,removeModule,placeDrive,defaultCircuit,emptyCircuits,validateCircuits,connect} from './circuit.js';
import {makePicker,makeDial} from './panel.js';
import {bindModuleDrag} from './circuit-drag.js';
export function createCircuitEditor({getValues,getSelected,onChange,onError}){
  const $=s=>document.querySelector(s),root=$('#circuit'),viewport=$('#circuit-viewport'),canvas=$('#circuit-canvas'),svg=$('#circuit-wires');
  let config=emptyCircuits(),active=false,pending=null,selectedWire=null,zoom=1,undo=[],redo=[],dragBindings=[];
  function stopDrags(){for(const dispose of dragBindings)dispose();dragBindings=[];}
  const originals=new Map([...document.querySelectorAll('#rack .module')].map(el=>[el.dataset.module,{el,parent:el.parentNode,next:el.nextSibling}]));
  const graph=()=>config.tracks[getSelected()];
  function notify(audio=true){onChange(getConfig(),audio);$('#circuit-routing').setAttribute('aria-pressed',graph().enabled);$('#circuit-routing').textContent=graph().enabled?'Routing On':'Routing Off';}
  function remember(){undo.push(structuredClone(config));if(undo.length>40)undo.shift();redo=[];$('#circuit-undo').disabled=false;$('#circuit-redo').disabled=true;}
  function change(fn,audio=true){try{stopDrags();const next=fn(structuredClone(graph()));remember();config.tracks[getSelected()]=next;notify(audio);render();return true;}catch(error){if(active)render();onError(error);return false;}}
  function restorePanels(){stopDrags();for(const {el,parent}of originals.values()){el.classList.remove('circuit-node');el.style.removeProperty('left');el.style.removeProperty('top');el.querySelectorAll('.circuit-ports,.circuit-remove').forEach(p=>p.remove());parent.append(el);}}
  function message(){const text=pending?`${MODULES[graph().nodes.find(n=>n.id===pending.node)?.kind]?.name??''}${pending.port==='out'?'':` ${pending.port.toUpperCase()}`} → choose an input`:selectedWire!=null?'Cable selected':'';$('#circuit-message').textContent=text;$('#circuit-disconnect').disabled=selectedWire==null;}
  function portButton(n,name,type,input){const button=document.createElement('button');button.type='button';button.className=`circuit-port ${type}`;button.dataset.port=name;button.dataset.node=n.id;button.dataset.direction=input?'in':'out';button.setAttribute('aria-label',`${MODULES[n.kind].name} ${n.id+1} ${input?'input':'output'} ${name}`);button.title=`${input?'Input':'Output'} · ${type.toUpperCase()} · ${name}`;
    const dot=document.createElement('span');dot.className='port-dot';button.append(dot,document.createTextNode(input?name:name==='out'?type.toUpperCase():name.toUpperCase()));
    button.addEventListener('click',()=>{selectedWire=null;if(!input){pending=pending?.node===n.id&&pending.port===name?null:{node:n.id,port:name};message();renderPorts();return;}
      if(pending!=null){const from=pending;try{const next=connect(graph(),from.node,n.id,name,from.port);stopDrags();remember();config.tracks[getSelected()]=next;pending=null;notify();render();}catch(error){onError(error);}return;}
      const index=graph().wires.findIndex(w=>w.to===n.id&&w.port===name);if(index>=0){selectedWire=index;message();drawWires();}
    });return button;}
  function renderPorts(){for(const button of canvas.querySelectorAll('.circuit-port')){const id=Number(button.dataset.node),out=button.dataset.direction==='out',port=button.dataset.port;button.setAttribute('aria-pressed',out&&id===pending?.node&&port===pending.port);button.classList.toggle('connected',out?graph().wires.some(w=>w.from===id&&(w.output??'out')===port):graph().wires.some(w=>w.to===id&&w.port===port));}}
  function wirePath(a,b){const bend=Math.max(48,Math.abs(b.x-a.x)*.5);return `M ${a.x} ${a.y} C ${a.x+bend} ${a.y}, ${b.x-bend} ${b.y}, ${b.x} ${b.y}`;}
  function drawWires(){svg.replaceChildren();const rect=canvas.getBoundingClientRect();const point=(id,dir,port)=>{const el=canvas.querySelector(`[data-node="${id}"][data-direction="${dir}"]${port?`[data-port="${port}"]`:''}`);if(!el)return;const r=el.getBoundingClientRect();return{x:(r.left+r.width/2-rect.left)/zoom,y:(r.top+r.height/2-rect.top)/zoom};};
    graph().wires.forEach((w,i)=>{const output=w.output??'out',a=point(w.from,'out',output),b=point(w.to,'in',w.port);if(!a||!b)return;const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',wirePath(a,b));path.setAttribute('class',`cable ${outputPorts(graph().nodes.find(n=>n.id===w.from).kind)[output]}${selectedWire===i?' selected':''}`);path.setAttribute('role','button');path.setAttribute('tabindex','0');path.setAttribute('aria-label',`Cable ${w.from+1}${output==='out'?'':` ${output.toUpperCase()}`} to ${w.to+1} ${w.port}`);const select=()=>{selectedWire=i;pending=null;message();drawWires();};path.addEventListener('click',select);path.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select();}});svg.append(path);});renderPorts();}
  function draggable(el,pos){const heading=el.querySelector('.module-heading');heading.classList.add('module-handle');heading.setAttribute('tabindex','0');heading.title='Drag to move · Arrow keys to move';
    const move=(x,y)=>{pos.x=Math.max(0,Math.min(9600,Math.round(x/4)*4));pos.y=Math.max(0,Math.min(9600,Math.round(y/4)*4));el.style.left=`${pos.x}px`;el.style.top=`${pos.y}px`;sizeCanvas();drawWires();};
    dragBindings.push(bindModuleDrag({heading,canvas,position:pos,getZoom:()=>zoom,onStart:remember,onMove:move,onEnd:()=>notify(false)}));
  }
  function controls(node,body){const controls=new Map(),refresh=()=>{const values=graph().nodes.find(n=>n.id===node.id)?.params??node.params;for(const [key,control]of controls){control.render(values[key]);if(node.kind==='oscillator1'&&key==='mode')control.button.disabled=values.wave>=4;}};for(const [key,[label,min,max,initial,options]]of Object.entries(MODULES[node.kind].controls??{})){
    const wrap=document.createElement('div'),text=document.createElement('label');wrap.className='parameter';text.textContent=label;wrap.append(text);let control;const update=value=>{remember();const params=graph().nodes.find(n=>n.id===node.id).params;params[key]=value;if(node.kind==='oscillator1'&&key==='wave'&&value>=4)params.mode=0;notify();refresh();};
    if(options){const picker=makePicker({label:`${MODULES[node.kind].name} ${node.id+1} ${label}`,options:options.map((label,value)=>({label,value})),value:node.params[key]??initial,onChange:update});control=picker;wrap.append(picker.button);}
    else{const value=node.params[key]??initial;const dial=makeDial({label:`${MODULES[node.kind].name} ${node.id+1} ${label}`,min,max,defaultValue:initial,read:()=>graph().nodes.find(n=>n.id===node.id)?.params[key]??initial,onChange:update,format:v=>String(v),step:key==='rate'?.01:1,numberStep:key==='rate'?.01:1,precision:key==='rate'?2:0});control=dial;wrap.append(dial.button,dial.number);dial.render(value);}controls.set(key,control);body.append(wrap);
  }refresh();}
  function render(){if(!active)return;restorePanels();canvas.querySelectorAll('.circuit-extra').forEach(el=>el.remove());pending=null;selectedWire=null;
    for(const n of graph().nodes){const def=MODULES[n.kind];let el=def.panel?originals.get(def.panel)?.el:null;
      if(!el){el=document.createElement('section');el.className=`module circuit-extra module-${n.kind}`;const head=document.createElement('div'),title=document.createElement('h2'),body=document.createElement('div');head.className='module-heading';title.textContent=def.name;head.append(title);body.className='module-controls';controls(n,body);el.append(head,body);}
      el.classList.add('circuit-node');el.dataset.circuitId=n.id;el.style.left=`${n.x}px`;el.style.top=`${n.y}px`;const ports=document.createElement('div');ports.className='circuit-ports';
      const inputs=document.createElement('div');inputs.className='circuit-inputs';for(const [name,type]of Object.entries(def.inputs??{}))inputs.append(portButton(n,name,type,true));ports.append(inputs);const outputs=document.createElement('div');outputs.className='circuit-outputs';for(const [name,type]of Object.entries(outputPorts(n.kind)))outputs.append(portButton(n,name,type,false));ports.append(outputs);el.append(ports);
      if(n.kind!=='output'){const remove=document.createElement('button');remove.className='circuit-remove';remove.type='button';remove.textContent='×';remove.setAttribute('aria-label',`Remove ${def.name} ${n.id+1}`);remove.addEventListener('click',()=>change(g=>removeModule(g,n.id)));el.querySelector('.module-heading').append(remove);}
      canvas.append(el);draggable(el,n);
    }
    for(const [key,pos]of Object.entries(graph().panels)){const el=originals.get(key)?.el;if(!el)continue;el.classList.add('circuit-node');el.style.left=`${pos.x}px`;el.style.top=`${pos.y}px`;canvas.append(el);draggable(el,pos);}
    message();notifyState();sizeCanvas();requestAnimationFrame(drawWires);
  }
  function fitViewport(){if(innerWidth>=1400&&innerHeight>=720){const dock=['.toolbar','.circuit-toolbar','.effects-rack','.sequencer','.performance-footer','#error'].reduce((height,selector)=>height+$(selector).offsetHeight,3);viewport.style.minHeight='200px';viewport.style.height=`${Math.max(200,innerHeight-dock)}px`;}else{viewport.style.removeProperty('height');viewport.style.removeProperty('min-height');}}
  function sizeCanvas(){fitViewport();const all=[...canvas.querySelectorAll('.circuit-node')],width=Math.max(1000,...all.map(el=>parseFloat(el.style.left)+el.offsetWidth+24)),height=Math.max(700,...all.map(el=>parseFloat(el.style.top)+el.offsetHeight+24));canvas.style.width=`${width}px`;canvas.style.height=`${height}px`;$('#circuit-space').style.width=`${width*zoom}px`;$('#circuit-space').style.height=`${height*zoom}px`;svg.setAttribute('viewBox',`0 0 ${width} ${height}`);}
  function notifyState(){$('#circuit-routing').setAttribute('aria-pressed',graph().enabled);$('#circuit-routing').textContent=graph().enabled?'Routing On':'Routing Off';$('#circuit-timbre').textContent=`TIMBRE ${getSelected()+1}`;$('#circuit-undo').disabled=!undo.length;$('#circuit-redo').disabled=!redo.length;add.options=[{value:'add',label:'Add module…'},...availableModules(graph()).map(value=>({value,label:MODULES[value].name+(value==='osc1'?' · Timbre':'')}))];}
  function getConfig(){return structuredClone(config);}
  function toggle(){active=!active;$('#build').setAttribute('aria-pressed',active);$('#build').textContent=active?'Rack':'Build';$('#rack').hidden=active;root.hidden=!active;document.body.dataset.build=active?'on':'off';if(active)render();else{restorePanels();for(const {el}of originals.values()){const h=el.querySelector('.module-heading');h.onpointerdown=h.onkeydown=null;h.classList.remove('module-handle');h.removeAttribute('tabindex');h.removeAttribute('title');}}}
  $('#build').addEventListener('click',toggle);
  $('#circuit-routing').addEventListener('click',()=>change(g=>{g.enabled=!g.enabled;return g;}));
  $('#circuit-disconnect').addEventListener('click',()=>{if(selectedWire==null)return;const index=selectedWire;change(g=>{g.wires.splice(index,1);g.enabled=true;return g;});});
  $('#circuit-reset').addEventListener('click',()=>change(()=>defaultCircuit(getValues())));
  $('#circuit-undo').addEventListener('click',()=>{if(!undo.length)return;redo.push(config);config=undo.pop();notify();render();});
  $('#circuit-redo').addEventListener('click',()=>{if(!redo.length)return;undo.push(config);config=redo.pop();notify();render();});
  const add=makePicker({label:'Add module',value:'add',options:[{value:'add',label:'Add module…'},...EXTRA_MODULES.map(value=>({value,label:MODULES[value].name}))],onChange:kind=>{
    add.render('add');if(!availableModules(graph()).includes(kind))return;
    if(!change(g=>{const id=Array.from({length:64},(_,i)=>i).find(id=>!g.nodes.some(n=>n.id===id));if(id==null)throw new Error('This timbre has 64 modules.');g.nodes.push({id,kind,params:Object.fromEntries(Object.entries(MODULES[kind].controls??{}).map(([key,c])=>[key,c[3]])),x:24,y:24});return g;}))return;
    const added=graph().nodes.at(-1),element=canvas.querySelector(`[data-circuit-id="${added.id}"]`),width=element.offsetWidth,height=element.offsetHeight;
    const existing=[...canvas.querySelectorAll('.circuit-node')].filter(el=>el!==element).map(el=>({x:parseFloat(el.style.left),y:parseFloat(el.style.top),w:el.offsetWidth,h:el.offsetHeight}));
    const rows=Math.max(1,Math.floor((10000-height)/24)),start=Math.min(rows-1,Math.floor(viewport.scrollTop/zoom/24));
    let x=24,y=24;outer:for(let row=0;row<rows;row++){y=((start+row)%rows+1)*24;for(x=24;x<2350;x+=350)if(existing.every(r=>x+width+16<r.x||x>r.x+r.w+16||y+height+16<r.y||y>r.y+r.h+16))break outer;}
    Object.assign(added,{x,y});element.style.left=`${x}px`;element.style.top=`${y}px`;sizeCanvas();drawWires();notify(false);
    viewport.scrollTo({left:Math.max(0,x*zoom-24),top:Math.max(0,y*zoom-24),behavior:'smooth'});
  }});$('#circuit-add').append(add.button);
  const scale=makePicker({label:'Canvas zoom',options:[50,75,100,125].map(value=>({value,label:`${value}%`})),value:100,onChange:value=>{stopDrags();zoom=value/100;canvas.style.transform=`scale(${zoom})`;render();}});$('#circuit-zoom').append(scale.button);
  document.addEventListener('keydown',e=>{if(!active||e.target.closest('input,textarea,dialog')||e.target.closest('.choice-popup'))return;if(e.key==='Escape'){pending=null;selectedWire=null;message();drawWires();}if((e.key==='Delete'||e.key==='Backspace')&&selectedWire!=null){e.preventDefault();$('#circuit-disconnect').click();}});
  const resize=new ResizeObserver(()=>{if(active){sizeCanvas();drawWires();}});resize.observe(viewport);resize.observe($('#effects'));
  return {getConfig,setConfig(raw){const next=validateCircuits(raw);stopDrags();config=next;undo=[];redo=[];if(active)render();},select(){pending=null;selectedWire=null;if(active)render();},positionDrive(value){if(!active&&!graph().enabled)return;try{const next=placeDrive(graph(),value);if(!next){onError(new Error('Custom Drive wiring: choose its destination with cables or a Switch.'));return;}if(JSON.stringify(next.wires)===JSON.stringify(graph().wires))return;remember();Object.assign(graph(),{wires:next.wires,enabled:next.enabled});pending=null;selectedWire=null;notify();if(active){message();drawWires();}}catch(error){onError(error);}},isActive:()=>active};
}
